### ISSUE TITLE
Memory leaks in client.c

### ISSUE THREAD

**Issue by m1k439** [ccrisan/streameye#1]
The methods write_response_ok_header() and write_response_auth_basic_header() both follow the following pattern:-

   malloc() a buffer
   sprintf() into the buffer
   return write_to_client(buffer)

which leaks the allocated memory; They should do something like:-

   malloc() a buffer
   sprintf() into the buffer
   rc = write_to_client(buffer)
   free( buffer );
   return rc;

**Comment by ccrisan** [comment]
You are right, that is a clear and plain memory leak. I remember writing it this way thinking that I'd make it right later, if the project succeeds. Obviously I forgot to do so :)

However, the incidence of the leak is irrelevant, given that `write_response_*` functions are called once, when the connection is established. The `write_multipart_header` which is called with each frame uses a statically allocated buffer.

I'll make sure to correct this, nevertheless.
