### ISSUE TITLE
Multiple streams one server

### ISSUE THREAD

**Issue by Classsic** [ccrisan/streameye#13]
Hi, is possible "push" multiple streams to differents paths, like rtmp server? I want to push to http://localhost:8080/camera1;http://localhost:8080/camera2; etc...one port, with multiple paths.
Thanks, great job.

**Comment by ccrisan** [comment]
I'm afraid that's not possible with streamEye and there are no plans to implement such a thing. One way to go about this is to use an efficient reverse proxy (such as nginx) in front of multiple streamEye instances.
