### ISSUE TITLE
Streaming MJPEG via HTTP from H264 RTSP source

### ISSUE THREAD

**Issue by sambul13** [ccrisan/streameye#2]
Is it possible to add support for on-the-fly conversion & streaming MJPEG over HTTP to LAN from a H264 RTSP Onvif IP Cam? Or how it can be done using FFMpeg and StreamEye instead of using FFServer?

**Comment by ccrisan** [comment]
This is probably the job of the ff\* suite. I don't have too much experience with ffmpeg/ffserver so I wouldn't know how to achieve this but it's clearly not something streamEye will ever do.
