### ISSUE TITLE
raspimjpeg.py - two line changes

### ISSUE THREAD

**Issue by fabiox23** [ccrisan/streameye#28]
If I read the code correctly, shouldn't it be:

line 94:
type=int, dest='contrast', default=0)

line 126: 
type=str, dest='imxfx', default=None,

**Comment by ccrisan** [comment]
Not necessarily: https://docs.python.org/3/library/argparse.html#dest.

*For optional argument actions, the value of dest is normally inferred from the option strings. ArgumentParser generates the value of dest by taking the first long option string and stripping away the initial -- string.*
