### ISSUE TITLE
Streaming MJPEG via HTTP from an MJPEG USB Source

### ISSUE THREAD

**Issue by sambul13** [ccrisan/streameye#3]
There is often a need to capture MJPEG stream from a USB Cam or analog cam & USB capture tandem in one place by a small Linux running ARM device, and then forward this stream without re-encoding over LAN to a more powerful processing server for analysis, recording, sending notifications, etc. Can you add this feature to StreamEye?

**Comment by ccrisan** [comment]
This can be achieved by using motion (see [motionEye](https://github.com/ccrisan/motioneye) and [motionEyeOS](https://github.com/ccrisan/motioneyeos)). streamEye could be used to do that but a v4l2 mjpeg grabber should be used in front of it. I'm not willing to add v4l2 capabilities to streamEye, if that's what you're asking.

**Comment by sambul13** [comment]
Hi Calin,

Thanks for your prompt reply. I've got a few ARMs and just found your software that seems to be carefully designed and well suited to complement Motion. That's why I wanted to contribute by leaving some suggestions based on daily tasks with various webcam types. If MotionEye allows to set forwarding such stream in its web UI via Motion and StreamEye tandem - its great, will try that, but I don't see such option in motionEye UI, so how to do that? :)
