### ISSUE TITLE
Audio Broadcast

### ISSUE THREAD

**Issue by ghost** [ccrisan/streameye#33]
Hey !
Is it possible to transfer an audio stream along with the video?

**Comment by ccrisan** [comment]
streamEye uses MJPEG to stream video data, and MJPEG does not support audio. So unfortunately this will be a no, we can't do that.

**Comment by ghost** [comment]
> StreamEye использует MJPEG для потоковой передачи видеоданных, а MJPEG не поддерживает аудио. Так что, к сожалению, это будет "нет", мы не можем этого сделать.

Thanks for the clarification
