### ISSUE TITLE
Installing Streameye

### ISSUE THREAD

**Issue by sambul13** [ccrisan/streameye#4]
How do I install streameye? The project page says nothing about it. I tried in Mint 17.3:
`sudo pip install streameye`

But it says:
`Could not find any downloads that satisfy the requirement streameye`

Can you add more detail install instructions to main project page? I previously install motioneye via pip and compiled motion-MrDave with all dependencies, but wanted to try streameye standalone.

**Comment by sambul13** [comment]
I now tried:

```
git clone https://github.com/ccrisan/streameye.git streameye
cd /home/linuxuser/streameye
sudo make
```

result:

```
linuxuser@Mint17 ~/streameye $ sudo make
cc -Wall -O2 -D_GNU_SOURCE -lpthread -o streameye streameye.o client.o auth.o
streameye.o: In function `main':
streameye.c:(.text.startup+0xd6f): undefined reference to `pthread_create'
streameye.c:(.text.startup+0x1252): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make: *** [streameye] Error 1
```

**Comment by ccrisan** [comment]
Is that a clean git clone? Try a make clean first. Never use sudo with make, unless installing.

**Comment by sambul13** [comment]
No change:

```
linuxuser@Mint17 ~/streameye $ make clean
rm -f *.o
rm -f streameye
linuxuser@Mint17 ~/streameye $ make
cc -Wall -O2 -D_GNU_SOURCE -c -o streameye.o streameye.c
cc -Wall -O2 -D_GNU_SOURCE -c -o client.o client.c
cc -Wall -O2 -D_GNU_SOURCE -c -o auth.o auth.c
cc -Wall -O2 -D_GNU_SOURCE -lpthread -o streameye streameye.o client.o auth.o
streameye.o: In function `main':
streameye.c:(.text.startup+0xd6f): undefined reference to `pthread_create'
streameye.c:(.text.startup+0x1252): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make: *** [streameye] Error 1

```

**Comment by ccrisan** [comment]
It may be a problem with the order of arguments and the -lpthread. I'll try this myself.

**Comment by ccrisan** [comment]
Could you please try the latest commit?

**Comment by sambul13** [comment]
This one compiled well. It seems to run with low overhead, convenient when streaming a remote source over lan for stream processing on a lan server. For example, when using a USB2.0 EasyCap Grabber with STK1160 chipset to grab a signal from analog cam and stream it over LAN:

ffmpeg -f video4linux2 -i /dev/video0 -framerate 30  -pixel_format uyvy422 -video_size ntsc -f mjpeg - 2>/dev/null | streameye
