### ISSUE TITLE
raspimjpeg error

### ISSUE THREAD

**Issue by ghost** [ccrisan/streameye#5]
I've got this error by  raspimjpeg:
Traceback (most recent call last):
  File "./raspimjpeg.py", line 250, in <module>
    run()
  File "./raspimjpeg.py", line 237, in run
    use_video_port=not options.stills, thumbnail=None, quality=options.quality)
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 1668, in capture_sequence
    encoder.wait()
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 853, in wait
    raise self.exception
IOError: [Errno 32] Broken pipe

What can I do to solve this?

**Comment by ccrisan** [comment]
What were you trying to do when this happened? Can you reproduce it? It normally indicates that the communication between the two processess (raspimjpeg and streamEye) was cut.

**Comment by ghost** [comment]
I was trying this command:
`python ./raspimjpeg.py -w 640 -h 480 -r 1 | streameye`

**Comment by ccrisan** [comment]
So (1) is it reproducible and (2) does it happen immediately when you run the command?

**Comment by ghost** [comment]
Yes everytime I use this command this error appears immediately

**Comment by ccrisan** [comment]
could you please try running the two commands separately? Try the following:

```
python ./raspimjpeg.py -w 640 -h 480 -r 1 > /dev/null
```

and then, simply:

```
streameye
```

See if any of them fails.

**Comment by ghost** [comment]
Yes the first command works!

Thanks!
